version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    restart: always
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/app
    links:
      - php
      - mysql
  mysql:
    image: "mysql"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=appdb
    ports:
      - 3306
  php:
    # image: php:7.1-fpm # without any extensions
    image: "nanoninja/php-fpm"
    ports:
      - 9000
    restart: always
    volumes:
      - ./app:/var/www/app