version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    restart: always
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/app
      - ./logs/nginx_access.log:/var/log/nginx/access.log
      - ./logs/nginx_error.log:/var/log/nginx/error.log
    links:
      - php
      - mysql
  mysql:
    image: "mysql"
    volumes:
      - ./mysql:/var/lib/mysql
    env_file: ./shared.env
  php:
    # image: php:7.1-fpm # without any extensions
    image: "nanoninja/php-fpm"
    restart: always
    volumes:
      - ./app:/var/www/app
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    env_file: ./shared.env
    user: www-data
